site_name: Black Nexus Technologies
site_description: News & Upcoming Releases
site_url: https://blacknexustechnologies.pages.dev/

theme:
  name: material
  features: 
    - navigation.sections
    - navigations.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins: 
  - search

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Servers: 
    - Abiotic Factor:
    - Arma 3:
    - Satisfactory:
  - Hardware Troubleshooting:


